# IN PROGRESS
# ------------------------------------------------ #
# 2bRAD Trim and QC Snakefile
# Kirsten Carlson
# Updated 1/2026
# ------------------------------------------------ #

# This Snakefile runs the pipeline for processing 2bRAD data.

# Scripts needed for this pipeline:
# From https://github.com/z0on/2bRAD_denovo
#  - trim2bRAD_2barcodes_dedup.pl
#  - uniquerOne.pl
#  - mergeUniq.pl
#  - concatFasta.pl

# ------------------------------------------------ #
# CONFIGURATION
# ------------------------------------------------ #

configfile: "../config/config.yaml"
# Project PRJNA number
prjna = config["prjna"]
# Conda environment
env = config["env"]
# Path to snakemake environment
env_path = config["env_path"]
# List of 2bRAD srr numbers and sample IDs
srr_2brad_list = config["srr_2brad_list"]
# List of ITS2 srr numbers and sample IDs
srr_its2_list = config["srr_its2_list"]
# Resource directory (SRR numbers, run info)
resource_dir = config["resource_dir"]
# Results directory
results_dir = config["results_dir"]
# Raw fastq file directory
rawfq_dir = config["rawfq_dir"]
# Raw QC file output directory
rawqc_dir = config["rawqc_dir"]
# Trimmed fastq file directory
trimfq_dir = config["trimfq_dir"]
# Trimmed QC file output directory
trimqc_dir = config["trimqc_dir"]
# Excluded symbiont trimmed fastq directory
trimfq_noSymb_dir = config["trimfq_noSymb_dir"]
# Aligned symbiont bam directory
symb_align_dir = config["symb_align_dir"]
# Aligned S. intersepta bam directory
sint_align_dir = config["sint_align_dir"]
# Merged unique reads directory
merge_dir = config["merge_dir"]
# De novo reference genome directory
denovo_ref_dir = config["denovo_ref_dir"]
# Standard Kraken database directory
kraken_db_std = config["kraken_db_std"]
# Custom Kraken database directory
kraken_db = config["kraken_db"]
# Script directory
scripts_dir = config["scripts_dir"]
# Parameter sweep for discoSnp_Rad
discosnp_kmers = config["discosnp_kmers"]
discosnp_dels = config["discosnp_dels"]
disco_percent_heterozygotes = config["disco_percent_heterozygotes"]
disco_percent_variants = config["disco_percent_variants"]
# Symbiont genomes
symbiont_genomes = config["symbiont_genomes"]
# Symbiont concatenated reference genome
reference_symbiont = config["reference_symbiont"]
# De novo reference genome
denovo_ref_basename = config["denovo_ref_basename"]
quality = config["quality"]
minlen = config["minlen"]


# ------------------------------------------------ #
# LOCA RULE FILES
# ------------------------------------------------ #
import pandas as pd

# Read SRR list to define final targets
srr_df = pd.read_csv(f"{config['resource_dir']}/samples_2brad.csv", sep=",", engine="python", header=0)
SRR_MAP = dict(zip(srr_df["SAMPLEID"], srr_df["SRR"]))
SAMPLES = list(SRR_MAP.keys())
SRR = list(SRR_MAP.values())

include: "rules/metadata.smk"
include: "rules/download.smk"
include: "rules/trim_qc.smk"
include: "rules/de_novo_symb_pipeline.smk"
include: "rules/discosnp.smk"

# Define final targets
rule all:
    input:
        # Metadata
        f"{resource_dir}/samples_2brad.csv",

        # Raw FASTQ (ensures download runs)
        expand(f"{rawfq_dir}/{{sample}}.fastq", sample=SAMPLES),

        # Raw QC
        expand(f"{rawqc_dir}/{{sample}}_fastqc.zip", sample=SAMPLES),
        f"{rawqc_dir}/multiqc_report.html",

        # Trimmed QC
        expand(f"{trimqc_dir}/{{sample}}_fastqc.zip", sample=SAMPLES),
        f"{trimqc_dir}/multiqc_report.html",

        # De novo reference
        f"{denovo_ref_dir}/cleanup.done",

        # DiscoSNP final outputs
        expand(
            f"{sint_align_dir}/discosnp/k{{k}}_D{{D}}/discoRad_k_{{k}}_c_3_D_{{D}}_P_5_m_5_filtered_hetero{{hetero}}_variants{{variants}}.vcf.gz",
            k=discosnp_kmers,
            D=discosnp_dels,
            hetero=config["disco_percent_heterozygotes"],
            variants=config["disco_percent_variants"]
        ),
        expand(
            f"{sint_align_dir}/discosnp/k{{k}}_D{{D}}/discoRad_k_{{k}}_D_{{D}}_slim.vcf.gz",
            k=discosnp_kmers,
            D=discosnp_dels
        ),
        expand(f"{sint_align_dir}/discosnp/k{{k}}_D{{D}}/discoRad_k_{{k}}_c_3_D_{{D}}_P_5_m_5_sorted_header_contigs_only.vcf.gz",
            k=discosnp_kmers,
            D=discosnp_dels
        ),

        # Reports
        f"{results_dir}/variant_report_before_filtering.txt",
        f"{results_dir}/variant_by_filter_report.txt",
        f"{results_dir}/paralog_variant_report.txt"
