# ------------------------------------------------ #
# 2bRAD Get Metadata Snakefile
# Kirsten Carlson
# Updated 1/2026
# ------------------------------------------------ #

# This Snakefile gets SRR numbers from PRJNA accession number.

# ------------------------------------------------ #
# CONFIGURATION
# ------------------------------------------------ #

configfile: "../config/config.yaml"
# PRJNA accession number
prjna = config["prjna"]
# Conda environment
env = config["env"]
# Resource directory (SRR numbers, run info)
resource_dir = config["resource_dir"]

# ------------------------------------------------ #
# RULES
# ------------------------------------------------ #

# This sequencing database has replicates that are not labeled as such in the SRA metadata. 
# This is a pre-made list of the SRR numbers and sample IDs for the 2bRAD samples, which was generated by manually checking the SRA metadata and run info for the project.
# ------------------------------------------------
rule srr_2brad_list:
    output:
        f"{resource_dir}/samples_2brad.csv"
    shell:
        """
        cd {scripts_dir}
        wget https://raw.githubusercontent.com/kirstencarlson-2025/coral_sequencing_project/refs/heads/main/resources/sample_rename.csv
        """


# Fetch run info from PRJNA accession number
# ------------------------------------------------
# rule fetch_srr:
#   output:
#        f"{resource_dir}/srr_runinfo.txt"
#    params:
#        prjna = config["prjna"]
#    shell:
#        """
#        esearch -db sra -query {params.prjna} | efetch -format runinfo > {output}
#        """

# Save SRR numbers to a list
# ------------------------------------------------
#rule srr_2brad_list:
#    input:
#        f"{resource_dir}/srr_runinfo.txt"
#    output:
#        f"{resource_dir}/srr_2brad_list.txt"
#    shell:
#        """
#        grep 2bRAD {input} | cut -f1,30 -d "," | grep SRR > {output}
#        """

# Save SRR ITS2 numbers to a list (optional)
# ------------------------------------------------
#rule srr_its2_list:
#    input:
#        f"{resource_dir}/srr_runinfo.txt"
#    output:
#        f"{resource_dir}/srr_its2_list.txt"
#    shell:
#        """
#        grep ITS2 {input} | cut -f1,30 -d "," | grep SRR > {output}
#        """
